spring:
  application:
    name: mz-office

  datasource:
    url: jdbc:mysql://172.17.0.1:3306/mzoffice?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: localpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
    open-in-view: false

app:
  jwtSecret: 5WOl8KinFPih9gSSZMyBkI9GBqCk1KNhZxmCHnJTT87MXf6o1Mneq/Q9QhCTTTct0cl23dRxfozp0GMGiRbKyA== #openssl rand -base64 64