spring:
  application:
    name: mz-office

  datasource:
    url: jdbc:mysql://localhost:3306/mzoffice?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://root:localpw@localhost:27017/mzoffice?authSource=admin

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        ddl-auto: none
    open-in-view: false

app:
  jwtSecret: 5WOl8KinFPih9gSSZMyBkI9GBqCk1KNhZxmCHnJTT87MXf6o1Mneq/Q9QhCTTTct0cl23dRxfozp0GMGiRbKyA== #openssl rand -base64 64

logging:
  level:
    org.hibernate: INFO
    org.springframework: INFO
