spring:
  application:
    name: mz-office

  profiles:
    active: prod

naver:
  requestTokenUri: https://nid.naver.com/oauth2.0/token
  userInfoUri: https://openapi.naver.com/v1/nid/me
  clientId: tz7UpvLovJSmalCKZQBW
  clientSecret: ${NAVER_CLIENT_SECRET}

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.bside.mzoffice
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true              # ?? ?? ??
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    enabled: true               # Swagger UI ???? : ?? ?? => <http://localhost:8080/swagger-ui/index.html>
    path: /api-swagger.html         # Swagger UI ?? ?? ?? =>
    tags-sorter: alpha          # alpha: ??? ? ?? ??, method: HTTP Method ? ??
    operations-sorter: alpha    # alpha: ??? ? ?? ??, method: HTTP Method ? ??

ai:
  key: ${AI_KEY}
  host: https://clovastudio.stream.ntruss.com/testapp/v1/chat-completions/HCX-003